version: '3'

services:
  api:
    build:
      context: api
      dockerfile: DockerfileProd
    image: lucassantos/api:latest
    container_name: api
    restart: always
    ports:
      - 3000:3000
    entrypoint: ['sh', '/home/node/init.sh']
    command: ["npm", "run", "start:prod"]
    networks:
      - prod_net

networks:
  prod_net:
    driver: bridge