@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJKb2huIERvZSIsImlhdCI6MTY5MzE2MzQ4OSwiZXhwIjoxNjkzMjQ5ODg5fQ.9F1vGmWh2O2FPWiCILaO9y16kZ0KlSWXOY0RBxY167A


### Helath Check
GET {{baseUrl}}/




### Auth
GET {{baseUrl}}/auth/student/me
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/auth/student
content-type: application/json

{
    "email": "john@doe.com",
    "password": "$2b$10$"
}

###
POST {{baseUrl}}/auth/student/register
content-type: application/json

{
    "email": "john@doe.com",
    "name": "John Doe",
    "password": "$2b$10$"
}




### Programming Languages
GET {{baseUrl}}/programming-languages
Authorization: Bearer {{{authToken}}}

###
GET {{baseUrl}}/programming-languages/7506837e-3f60-4b11-99a0-98f131854999
Authorization: Bearer {{{authToken}}}




### Modules
GET {{baseUrl}}/modules
Authorization: Bearer {{{authToken}}}

###
GET {{baseUrl}}/modules/1
Authorization: Bearer {{{authToken}}}

###
GET {{baseUrl}}/programming-languages/7506837e-3f60-4b11-99a0-98f131854999/modules
Authorization: Bearer {{{authToken}}}




### Levels
GET {{baseUrl}}/levels/1
Authorization: Bearer {{{authToken}}}




### MiniGames
POST {{baseUrl}}/mini-games/1/register-answer
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "answer": true
}