@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YzdmMzcwYS03YTAzLTQ2OGMtOTY5Ny0wNWFjYzM0Y2ZkN2QiLCJ1c2VybmFtZSI6Ikx1Y2FzIFNhbnRvcyIsImlhdCI6MTY5NDkwMjQ1NywiZXhwIjoxNjk0OTE2ODU3fQ.V7Stn_45a3BMWHPJTWtyUXEqguNy20e5_gydAjm34ag
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YzdmMzcwYS03YTAzLTQ2OGMtOTY5Ny0wNWFjYzM0Y2ZkN2QiLCJ1c2VybmFtZSI6Ikx1Y2FzIFNhbnRvcyIsInJlZnJlc2giOnRydWUsImlhdCI6MTY5NDkwMjQ1NywiZXhwIjoxNjk1NTA3MjU3fQ.QmKBqj9PCXliYzNgo899kHfMYWtKWDX3XAPP6n9L92Q

### Helath Check
GET {{baseUrl}}/




### Auth
GET {{baseUrl}}/auth/student/me
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/auth/student
content-type: application/json

{
    "email": "lucas@teste.tst",
    "password": "Teste123@"
}

###
POST {{baseUrl}}/auth/student/refresh
content-type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
POST {{baseUrl}}/auth/student/register
content-type: application/json

{
    "email": "lucas@teste.tst",
    "name": "Lucas Santos",
    "password": "Teste123@"
}




### Programming Languages
GET {{baseUrl}}/programming-languages
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/programming-languages/7506837e-3f60-4b11-99a0-98f131854999
Authorization: Bearer {{authToken}}




### Modules
GET {{baseUrl}}/modules
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/modules/1
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/programming-languages/7506837e-3f60-4b11-99a0-98f131854999/modules
Authorization: Bearer {{authToken}}




### Levels
GET {{baseUrl}}/levels/1465f146-ebaf-4a12-abda-d9281a37c386
Authorization: Bearer {{authToken}}




### MiniGames
POST {{baseUrl}}/mini-games/1/register-answer
content-type: application/json
Authorization: Bearer {{authToken}}

{
    "answer": true
}